aws s3 cp CAvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-ca/
aws s3 cp DEvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-de/
aws s3 cp FRvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-fr/
aws s3 cp GBvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-gb/
aws s3 cp INvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-in/
aws s3 cp JPvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-jp/
aws s3 cp KRvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-kr/
aws s3 cp MXvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-mx/
aws s3 cp RUvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-ru/
aws s3 cp USvideos.csv s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics/region-us/

aws s3 cp CA_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-ca/
aws s3 cp DE_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-de/
aws s3 cp FR_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-fr/
aws s3 cp GB_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-gb/
aws s3 cp IN_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-in/
aws s3 cp JP_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-jp/
aws s3 cp KR_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-kr/
aws s3 cp MX_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-mx/
aws s3 cp RU_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-ru/
aws s3 cp US_category_id.json s3://yt-datapipeline-bronze-ap-south-1/youtube/raw-statistics-reference-data/region-us/
